### ISSUE TITLE
 Could not find or load main- while installing

### ISSUE THREAD

**Issue by sabalalani** [olk90/BarcodeGenerator#1]
Below error shows up when I run the BarcodeGenerator.bat file
Could not find or load main class org.tornadofx.barcodegenerator.app.BarcodeGeneratorApp
I have used BarcodeGenerator_v0.1 release.

**Comment by olk90** [comment]
Hi, what version of Java are you running on your machine? Check out by running `java -version` in the windows command line. 

This is most likely related to a JRE/JDK newer than Java 8. These do not ship with required JavaFX dependencies, so using a OpenJDK build containing JFX. Such a build can be found [here](https://www.azul.com/downloads/?version=java-8-lts&os=windows&package=jdk-fx) for instance.

I will migrate the tool to the latest versions of Java, as soon as there is a release of [TornadoFX2](https://github.com/edvin/tornadofx2) available.

**Comment by sabalalani** [comment]
oh okay, 
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

**Comment by olk90** [comment]
Okay, this looks like you are running Oracle Java 8, which *should* work. I need to get my hands on a running Windows machine. Coming back to you, as soon as I know more.

**Comment by sabalalani** [comment]
Sure

**Comment by olk90** [comment]
So, on a Windows machine without any Java installed previously, I've

* installed Oracle's JRE 8 (same version that runs on your machine).  
* downloaded and unpacked the BarcodeGenerator 
* executing `BarcodeGenerator.bat` launched the program without any issues

I need some more information:

* What Windows version do you have? I've tested it on a 64 bit Win10. 
*  Are you facing similar issues with other programs requiring Java?

**Comment by sabalalani** [comment]
Hi,

Mine is win 10 64 bit as well. Currently, not facing it with other apps
requiring JAVA. Also, I tried openjdk too. It gives the same error.

**Comment by olk90** [comment]
I was able to gain a similar error when executing the program from a JAR file. I've fixed that, please check out [the new pre-release](https://github.com/olk90/BarcodeGenerator/releases/tag/v0.1.1-beta) and execute the JAR file.

**Comment by sabalalani** [comment]
Now its showing up below error:
Error: Could not find or load main class
de.olk90.barcodegenerator.app.BarcodeGeneratorApp

**Comment by olk90** [comment]
I tested it on my Windows machine:

* Downloaded jar file [BarcodeGenerator-0.1.1.jar](https://github.com/olk90/BarcodeGenerator/releases/download/v0.1.1-beta/BarcodeGenerator-0.1.1.jar)
* launched it from the Windows command line via `java -jar BarcodeGenerator-0.1.1.jar`
    * program launches without issues
    * when executing the command `java BarcodeGenerator-0.1.1.jar` (without the `-jar` flag), I receive an error about the missing main class as well

**Comment by sabalalani** [comment]
I dont know what is the problem :(
![image](https://user-images.githubusercontent.com/86874627/124380868-b1dc8d00-dcd8-11eb-8a5e-6e91cf31f472.png)

**Comment by olk90** [comment]
I' a bit baffled, too :disappointed: 

I'll ask around for help, sorry.

**Comment by olk90** [comment]
I have done some refactoring in the build file. Furthermore, the [pre-release](https://github.com/olk90/BarcodeGenerator/releases/tag/v0.1.1-beta) was extended with a native EXE for Windows. On my Windows machine both launch without issues.

**Comment by olk90** [comment]
Closed due to inactivity
